name: Check image

on: [push, pull_request, workflow_dispatch]

env:
  cache-version: v1

jobs:
  r-build-and-check:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: TRUE
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CRAN: https://packagemanager.posit.co/cran/__linux__/noble/latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Query dependencies and update old packages
        run: |
          options(repos = c(CRAN = Sys.getenv("CRAN")))
          BiocManager::install(c("remotes", "rcmdcheck"), ask = FALSE)
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v5
        with:
          path: /usr/local/lib/R/site-library
          key: ${{ env.cache-version }}-${{ runner.os }}-r-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ env.cache-version }}-${{ runner.os }}-r-

      - name: Install dependencies
        run: |
          options(repos = c(CRAN = Sys.getenv("CRAN")))
          remotes::install_deps(dependencies = TRUE, repos = BiocManager::repositories())
          BiocManager::install(ask = FALSE, update = TRUE)
        shell: Rscript {0}

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Build pkgdown
        run: |
          PATH=$PATH:$HOME/bin/ Rscript -e 'pkgdown::build_site(".")'

      - name: Upload pkgdown artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v7
        with:
          name: pkgdown-site
          path: docs
